############### Key-Bind #################
# Prefix(Ctrl-b -> Ctrl-a)
set -g prefix C-a
unbind C-b

# Pane Split
bind s split-window -h -c '#{pane_current_path}'
bind v split-window -v -c '#{pane_current_path}'

# Pane Move
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


############### Look and Feel #################
# Color
set -g default-terminal "screen-256color"
set -g terminal-overrides "xterm:colors=256"

# Statusline
set-option -g status-interval 1
set-option -g status-justify "left"
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"
set-option -g status-left "#[fg=colour255,bg=colour241] TMUX Session: #S #[fg=colour241,bg=colour238]\uE0B0#[default]"
set-option -g status-left-length 100
set-option -g status-right "#{battery_icon} #{battery_percentage} \uE0B3  %m/%d(%a) \uE0B3 󰥔 %H:%M:%S #[default]"
set-option -g status-right-length 150
set-window-option -g window-status-format "#[fg=colour255,bg=colour238,bold] #I:#W #[fg=colour255,bg=colour238]\uE0B1#[default]"
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold] #I:#W #[fg=colour27,bg=colour238]\uE0B0#[default]"

############### Misc #################
# Mouse wheel
set-option -g mouse on
set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'

# for vim
set escape-time 5

############### Plugins #################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'
run '~/.tmux/plugins/tpm/tpm'

############### tmux-battery configuration
# Level of charge color : background color
set -g @batt_color_charge_primary_tier8 '#00ff00' #[95%-100%]
set -g @batt_color_charge_primary_tier7 '#55ff00' #[80%-95%)
set -g @batt_color_charge_primary_tier6 '#aaff00' #[65%-80%)
set -g @batt_color_charge_primary_tier5 '#ffff00' #[50%-65%)
set -g @batt_color_charge_primary_tier4 '#ffc000' #[35%-50%)
set -g @batt_color_charge_primary_tier3 '#ff8000' #[20%-35%)
set -g @batt_color_charge_primary_tier2 '#ff4000' #(5%-20%)
set -g @batt_color_charge_primary_tier1 '#ff0000' #[0%-5%)
# Level of charge color : foreground color
set -g @batt_color_charge_secondary_tier8 'colour0' #[95%-100%]
set -g @batt_color_charge_secondary_tier7 'colour0' #[80%-95%)
set -g @batt_color_charge_secondary_tier6 'colour0' #[65%-80%)
set -g @batt_color_charge_secondary_tier5 'colour0' #[50%-65%)
set -g @batt_color_charge_secondary_tier4 'colour0' #[35%-50%)
set -g @batt_color_charge_secondary_tier3 'colour0' #[20%-35%)
set -g @batt_color_charge_secondary_tier2 'colour0' #(5%-20%)
set -g @batt_color_charge_secondary_tier1 'colour0' #[0%-5%)


# Level of charge icons
set -g @batt_icon_charge_tier8 '󰁹' #[95%-100%]
set -g @batt_icon_charge_tier7 '󰂂' #[80%-95%)
set -g @batt_icon_charge_tier6 '󰂀' #[65%-80%)
set -g @batt_icon_charge_tier5 '󰁾' #[50%-65%)
set -g @batt_icon_charge_tier4 '󰁽' #[35%-50%)
set -g @batt_icon_charge_tier3 '󰁻' #[20%-35%)
set -g @batt_icon_charge_tier2 '󰁺' #(5%-20%)
set -g @batt_icon_charge_tier1 '󱃍' #[0%-5%)
# Status icons
set -g @batt_icon_status_charged '󱟢'
set -g @batt_icon_status_charging '󰂊'
set -g @batt_icon_status_discharging '👎'
set -g @batt_color_status_primary_charged '#3daee9'
set -g @batt_color_status_primary_charging '#3daee9'
set -g @battery_color_bg '#3daee9'
set -g @battery_color_fg '#eeeeee'
