vim.api.nvim_create_user_command("Restart", function()
	local session = vim.fs.joinpath(tostring(vim.fn.stdpath("state")), "restart_session.vim")
	vim.fn.mkdir(vim.fs.dirname(session), "p")
	vim.cmd.mksession({ args = { session }, bang = true })
	vim.cmd.restart({ args = { "source", session } })
end, { desc = "Restart current neovim session" })
