return {
	"stevearc/aerial.nvim",
	enabled = true,
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-tree/nvim-web-devicons",
	},
	event = "VeryLazy",
	keys = {
		{ mode = { "n" }, "go", "<cmd>AerialToggle float<CR>", desc = "LSP Outline" },
	},
	config = function()
        require("telescope").load_extension("aerial")
		require("aerial").setup({
			backends = { "treesitter", "lsp", "markdown" },
			layout = {
				max_width = { 100, 0.5 },
				-- width = nil,
				min_width = 50,
				resize_to_content = true,
			},
			highlight_on_hover = true,
			-- attach_mode = "window",
			autojump = true,
			show_guides = true,
			float = {
				border = "rounded",
				relative = "editor",
				-- max_height = 0.9,
				-- height = 0.5,
				-- min_height = { 8, 0.3 },
			},
			keymaps = {
				["go"] = "actions.close",
			},
			nerd_font = "mini.icons",
			filter_kind = {
				"Array",
				"Boolean",
				"Class",
				"Constant",
				"Constructor",
				"Enum",
				"EnumMember",
				"Event",
				"Field",
				"File",
				"Function",
				"Interface",
				"Key",
				"Method",
				"Module",
				"Namespace",
				"Null",
				"Number",
				"Object",
				"Operator",
				"Package",
				"Property",
				"String",
				"Struct",
				"TypeParameter",
				"Variable",
			},
			icons = {
				Array = "󰅪 Array",
				Boolean = "󰨙 Bool",
				Class = "󰆧 Class",
				Constant = "󰏿 Constant",
				Constructor = " Constructor",
				Enum = " Enum ",
				EnumMember = " EnumMember",
				Event = " Event ",
				Field = " Field",
				File = "󰈙 File",
				Function = "󰊕 Fn",
				Interface = " Interface",
				Key = "󰌋 Key",
				Method = "󰊕 Method",
				Module = " Module",
				Namespace = "󰦮 Namespace",
				Null = "󰟢 Null",
				Number = "󰎠 Number",
				Object = " Object",
				Operator = "󰆕 Operator",
				Package = " Package",
				Property = " Property",
				String = " String",
				Struct = "󰆼 Struct",
				TypeParameter = "󰗴 TypeParam",
				Variable = "󰀫 Variable",
				Collapsed = " ",
				rust = {
					Class = "impl",
					Struct = "struct",
					Enum = "enum",
					Function = "fn",
					Module = "mod",
					Method = "fn",
					Interface = "trait",
				},
				typescript = {
					Class = "class",
					Function = "function",
					Method = "function",
					Interface = "interface",
				},
				python = {
					Class = "class",
					Function = "def",
					Method = "def",
				},
				markdown = {
					Interface = "Header",
				},
				yaml = {
					Class = " ",
					Enum = " ",
				},
			},
		})
	end,
}
