os:
  editPreset: 'nvim'
keybinding:
  universal:
    scrollUpMain: '<c-k>'
    scrollDownMain: '<c-j>'
customCommands:
  - key: <c-l>
    description: Pick AI commit
    command: aicommit2
    context: files
    output: terminal
