# local構成向けの上書き設定。
# ~/.config/tmux/local.conf に記号リンクされた場合のみ .tmux.conf から読み込まれる。

# Prefix を既定の Ctrl+b に戻す
set -g prefix C-b
unbind C-a
bind C-b send-prefix

# tmux2k のテーマを duo にする
set -g @tmux2k-theme 'duo'
