# Global Install tools
[tools]
# ProgramLanguage and Ecosystems
rustup = "latest"
uv = "latest"
pnpm = "latest"
clang = "latest"
clang-format = "latest"
clangd = "latest"
cmake = "latest"
gcc = "latest"
make = "latest"

# Editor and Improve Terminal Environment
neovim = "latest"
tmux = "latest"
lazygit = "latest"
starship = "latest"
ripgrep = "latest"
fzf = "latest"
lsd = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
bottom = "latest"

# LLM
claude = "latest"

# Misc
tree-sitter = "latest"
zip = "latest"
unzip = "latest"
